### ISSUE TITLE
make html error

### ISSUE THREAD

**Issue by radhikavm** [abelardopardo/ontask_b#6]
Going through the installation steps tend to get the following errors at 
step: 11 ```make html```

```
Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/__main__.py", line 14, in <module>
    sys.exit(main(sys.argv))
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/__init__.py", line 66, in main
    sys.exit(build_main(argv))
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/__init__.py", line 76, in build_main
    from sphinx import cmdline
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/cmdline.py", line 14, in <module>
    import optparse
  File "/home/ec2-user/anaconda2/lib/python2.7/optparse.py", line 419, in <module>
    _builtin_cvt = { "int" : (_parse_int, _("integer")),
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 642, in gettext
    return dgettext(_current_domain, message)
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 606, in dgettext
    codeset=_localecodesets.get(domain))
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 541, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 513, in find
    for nelang in _expand_lang(lang):
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 206, in _expand_lang
    from locale import normalize
ImportError: cannot import name normalize
make: *** [html] Error 1
```

And also :
step 9 : ```python manage.py loaddata ontask/initial_data.json```
 (file not present the mentioned path)

**Comment by abelardopardo** [comment]
Fixed. The initial data has now been moved to a script. Should now install without problems.
