### ISSUE TITLE
make html error

### ISSUE THREAD

**Issue by radhikavm** [abelardopardo/ontask_b#7]
python version :  ``` Python 2.7.13 :: Anaconda 4.3.0 (64-bit)``` 
While executing Step 1: ```make html``` 
get following error
```Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/__main__.py", line 14, in <module>
    sys.exit(main(sys.argv))
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/__init__.py", line 66, in main
    sys.exit(build_main(argv))
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/__init__.py", line 76, in build_main
    from sphinx import cmdline
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/cmdline.py", line 14, in <module>
    import optparse
  File "/home/ec2-user/anaconda2/lib/python2.7/optparse.py", line 419, in <module>
    _builtin_cvt = { "int" : (_parse_int, _("integer")),
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 642, in gettext
    return dgettext(_current_domain, message)
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 606, in dgettext
    codeset=_localecodesets.get(domain))
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 541, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 513, in find
    for nelang in _expand_lang(lang):
  File "/home/ec2-user/anaconda2/lib/python2.7/gettext.py", line 206, in _expand_lang
    from locale import normalize
ImportError: cannot import name normalize
make: *** [html] Error 1```

**Comment by abelardopardo** [comment]
It is a strange error. I just searched for some clues, and there may be more than one version of sphinx interacting in the platform (https://stackoverflow.com/questions/44892987/sphinx-error-can-not-import-normalize-while-using-command-make-html)

Can you try if your python interpreter can "from locale import normalize" without any errors? If so, I think it is possible that this is a python configuration problem in your project. Make sure it is picking up the right version.

**Comment by radhikavm** [comment]
Turns out for some odd reason - Sphinx was installed incorrectly,  uninstalled and re-installed it and it worked.

**Comment by abelardopardo** [comment]
Good to hear. Thanks for the msg
